# Support Vector Machines
You should build a machine learning pipeline using a support vector machine model. In particular, you should do the following:
- Load the `mnist` dataset using [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html). You can find this dataset in the datasets folder.
- Split the dataset into training and test sets using [Scikit-Learn](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html).
- Conduct data exploration, data preprocessing, and feature engineering if necessary.
- Train and test a support vector machine model using [Scikit-Learn](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html).
- Check the documentation to identify the most important hyperparameters, attributes, and methods of the model. Use them in practice.

In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler

In [30]:
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import (classification_report, accuracy_score, confusion_matrix,
precision_score, recall_score, f1_score)


In [8]:
df = pd.read_csv("https://raw.githubusercontent.com/m-mahdavi/teaching/refs/heads/main/datasets/mnist.csv")
df.head()

,id,class,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,31953,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,34452,8,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,60897,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,36953,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1981,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [12]:
print("Dataset sample:")
print(df.head)


Dataset sample:
<bound method NDFrame.head of          id  class  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0     31953      5       0       0       0       0       0       0       0   
1     34452      8       0       0       0       0       0       0       0   
2     60897      5       0       0       0       0       0       0       0   
3     36953      0       0       0       0       0       0       0       0   
4      1981      3       0       0       0       0       0       0       0   
...     ...    ...     ...     ...     ...     ...     ...     ...     ...   
3995  25268      1       0       0       0       0       0       0       0   
3996   6473      6       0       0       0       0       0       0       0   
3997   5821      7       0       0       0       0       0       0       0   
3998   1751      9       0       0       0       0       0       0       0   
3999  56752      2       0       0       0       0       0       0       0   

      pixel8  ...

In [35]:
X = df.drop(columns=["id", "class"])
Y = df["class"]
X_train, X_test,Y_train,Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [24]:
model = SVC(kernel="linear", C=1.0, random_state=42)
model.fit(X_train, Y_train)

SVC(kernel='linear', random_state=42)

In [27]:
y_pred = model.predict(X_test)
print("\nAccuracy:", accuracy_score(Y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(Y_test, y_pred))
print("\nClassification Report:\n", classification_report(Y_test, y_pred))


Accuracy: 0.90125

Confusion Matrix:
 [[69  0  0  0  0  1  0  0  0  0]
 [ 0 98  0  1  0  0  0  0  1  0]
 [ 1  2 64  2  2  0  1  0  1  0]
 [ 0  0  4 71  1  7  0  1  2  0]
 [ 0  0  0  0 76  0  1  0  1  2]
 [ 1  3  0  0  1 53  2  1  3  0]
 [ 1  0  4  0  0  2 83  0  0  0]
 [ 0  0  0  1  1  0  0 63  0  2]
 [ 1  1  3  2  2  5  0  0 78  2]
 [ 0  0  1  1  6  0  0  2  0 66]]

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.99      0.97        70
           1       0.94      0.98      0.96       100
           2       0.84      0.88      0.86        73
           3       0.91      0.83      0.87        86
           4       0.85      0.95      0.90        80
           5       0.78      0.83      0.80        64
           6       0.95      0.92      0.94        90
           7       0.94      0.94      0.94        67
           8       0.91      0.83      0.87        94
           9       0.92      0.87      0.89        76

    accur

In [31]:
acc = accuracy_score(y_pred=y_pred, y_true=Y_test)
prec = precision_score(y_pred=y_pred, y_true=Y_test, average="macro")
rec = recall_score(y_pred=y_pred, y_true=Y_test, average="macro")
f1 = f1_score(y_pred=y_pred, y_true=Y_test, average="macro")
print("Accuracy: ", acc)
print("Precision: ", prec)
print("Recall: ", rec)
print("F1 Score: ", f1)

print("\nDetailed Classification Report:\n", classification_report(y_pred=y_pred, y_true=Y_test))

Accuracy:  0.90125
Precision:  0.8991184100970744
Recall:  0.9006862026189287
F1 Score:  0.8989882100401454

Detailed Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.99      0.97        70
           1       0.94      0.98      0.96       100
           2       0.84      0.88      0.86        73
           3       0.91      0.83      0.87        86
           4       0.85      0.95      0.90        80
           5       0.78      0.83      0.80        64
           6       0.95      0.92      0.94        90
           7       0.94      0.94      0.94        67
           8       0.91      0.83      0.87        94
           9       0.92      0.87      0.89        76

    accuracy                           0.90       800
   macro avg       0.90      0.90      0.90       800
weighted avg       0.90      0.90      0.90       800



In [34]:
cv_scores = cross_val_score(model, X_train, Y_train, cv=5)
print("Cross-Validation Scores:", cv_scores)
print("Mean CV Score:", np.mean(cv_scores))

Cross-Validation Scores: [0.903125  0.9078125 0.921875  0.89375   0.9171875]
Mean CV Score: 0.9087500000000001
